[package]
name = "gol_py"
version = "0.1.0"
authors = ["taylorlee"]

[dependencies]
game = { path = "../game" }

[dependencies.pyo3]
version = "0.2.0"
default-features = false

[lib]
crate-type = ["cdylib"]
name = "gol_py"
