[package]
name = "gol_py"
version = "0.1.0"
authors = ["<fafhrd91@gmail.com>"]

[dependencies]
game_of_life = { path = "../../game_of_life" }

[dependencies.pyo3]
version = "0.2.0"
default-features = false

[lib]
crate-type = ["cdylib"]
name = "helloworld"
